'use strict';

const fspDefault = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { randomUUID: randomUUIDDefault } = require('node:crypto');

// Windows-native offline dictation fallback for OAuth Live voice. The command is entirely static: no user
// text enters PowerShell. System.Speech listens to the default microphone after the user explicitly starts
// Live voice, returns one utterance, then disposes the recognizer.
//
// ⛔ THE OUTPUT CARRIES CONFIDENCE, AND IT IS NOT DECORATION. A DictationGrammar answers a cough, a fan or a
// door with a real-looking short word ("Mm."), and the caller turns any non-empty transcript into a full agent
// run. Unattended, that spends a provider meter on room noise and earns a genuine upstream rate-limit — which
// then looks like "the model is broken". The Whisper path never had this problem because it gates on audio
// energy first; this leg had no gate at all, so the engine's own Confidence is what we gate on instead.
// Confidence is emitted as an INTEGER per-mille (`842|hello world`) deliberately: PowerShell's `{0:N3}` uses
// the current culture, so a machine with a decimal-comma locale would emit "0,842" and any parse of it would
// silently read as 0.
const WINDOWS_SCRIPT = [
  "$ErrorActionPreference='Stop'",
  'Add-Type -AssemblyName System.Speech',
  "[Console]::OutputEncoding=[Text.Encoding]::UTF8",
  '$r=New-Object System.Speech.Recognition.SpeechRecognitionEngine',
  '$r.LoadGrammar((New-Object System.Speech.Recognition.DictationGrammar))',
  '$r.SetInputToDefaultAudioDevice()',
  '$x=$r.Recognize([TimeSpan]::FromSeconds(15))',
  "if($null -ne $x){Write-Output ('{0}|{1}' -f [int]($x.Confidence*1000),$x.Text)}",
  '$r.Dispose()'
].join(';');

// Standard click-to-talk records one bounded take in the browser. Feed that exact take to the same local
// recognizer instead of letting System.Speech decide the endpoint from a pause. The path is generated by the
// sidecar, passed out-of-band in the child environment (never interpolated into the command), and removed in
// finally below.
const WINDOWS_WAV_SCRIPT = [
  "$ErrorActionPreference='Stop'",
  'Add-Type -AssemblyName System.Speech',
  "[Console]::OutputEncoding=[Text.Encoding]::UTF8",
  '$r=New-Object System.Speech.Recognition.SpeechRecognitionEngine',
  '$r.LoadGrammar((New-Object System.Speech.Recognition.DictationGrammar))',
  '$r.SetInputToWaveFile($env:STARNET_NATIVE_STT_WAV)',
  // ONE Recognize() returns ONE phrase (it ends at a pause), so a two-click take "Open the report. Then
  // summarize it." kept only its first sentence. Read phrase after phrase until Recognize() returns null — at the
  // end of the file, or (System.Speech's own rule) on a stretch it rejects outright; measured with 1.5s of white
  // noise between two sentences it still returned both. The cap bounds a pathological stream. One "conf|text"
  // line per phrase.
  '$n=0',
  "while($n -lt 40 -and $null -ne ($x=$r.Recognize())){$n++;Write-Output ('{0}|{1}' -f [int]($x.Confidence*1000),$x.Text)}",
  '$r.Dispose()'
].join(';');

// Non-lexical sounds a dictation grammar reaches for when it hears noise. Deliberately short and
// conservative: only utterances that carry no instruction on their own. A real one-word command ("stop",
// "yes", "no") must still get through, so those are NOT here.
const NOISE_TOKENS = /^(?:m+|h+m+|m+h+m*|u+h+|u+m+|a+h+|o+h+|e+r+|h+u+h|h+a+)[.,!?]*$/i;
const DEFAULT_MIN_CONFIDENCE = 0.4;

function minConfidence(env) {
  const raw = (env || process.env).STARNET_NATIVE_STT_MIN_CONFIDENCE;
  const n = Number(raw);
  // An unset or unparseable override must not silently disable the gate.
  return Number.isFinite(n) && n >= 0 && n <= 1 ? n : DEFAULT_MIN_CONFIDENCE;
}

/* Split `842|hello world` into its parts. A line with no separator is treated as text with UNKNOWN
   confidence (null) rather than confidence 0 — an older script, or a future one, must not have every
   utterance silently dropped by a gate that mistakes "not reported" for "not confident". */
function parseRecognition(stdout) {
  const raw = String(stdout || '').replace(/\r?\n/g, ' ').trim();
  if (!raw) return { text: '', confidence: null };
  const m = /^(\d{1,4})\|([\s\S]*)$/.exec(raw);
  if (!m) return { text: raw.slice(0, 4000), confidence: null };
  const permille = Number(m[1]);
  return {
    text: String(m[2] || '').trim().slice(0, 4000),
    confidence: Number.isFinite(permille) ? Math.max(0, Math.min(1, permille / 1000)) : null
  };
}

/* Is this transcript substantial enough to spend a run on? Returns '' for anything that should be treated
   as silence. The caller re-arms on an empty transcript, so a drop costs the user nothing but a re-listen. */
function gateTranscript(text, confidence, floor) {
  const t = String(text || '').replace(/\s+/g, ' ').trim();
  if (!t) return '';
  if (!/[a-z0-9]/i.test(t)) return '';                       // punctuation-only
  if (NOISE_TOKENS.test(t)) return '';                       // "Mm." and friends, at ANY confidence
  if (confidence != null && confidence < floor) return '';    // the engine itself is unsure
  return t;
}

function makeNativeStt(opts) {
  opts = opts || {};
  const platform = opts.platform || process.platform;
  const execFile = opts.execFile;
  const floor = minConfidence(opts.env);
  const fsp = opts.fsp || fspDefault;
  const tempDir = typeof opts.tempDir === 'string' ? opts.tempDir : os.tmpdir();
  const randomUUID = opts.randomUUID || randomUUIDDefault;
  const processEnv = opts.processEnv || process.env;

  function status() {
    return {
      available: platform === 'win32' && typeof execFile === 'function',
      engine: platform === 'win32' ? 'windows-system-speech' : 'unsupported',
      minConfidence: floor
    };
  }

  function runRecognition(script, signal, audioPath, audioMs) {
    return new Promise(resolve => {
      const options = {
        windowsHide: true,
        // A long take is read phrase by phrase: allow for its own length, never less than the old 20s.
        timeout: Math.max(20000, Math.round((audioMs || 0) * 1.5) + 10000),
        maxBuffer: 1 << 16,
        encoding: 'utf8'
      };
      if (signal) options.signal = signal;
      if (audioPath) options.env = Object.assign({}, processEnv, { STARNET_NATIVE_STT_WAV: audioPath });
      execFile('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command', script], options, (error, stdout) => {
        // Each phrase is gated on its own: a cough between two real sentences must not cost either of them.
        const phrases = String(stdout || '').split(/\r?\n/).filter(line => line.trim()).map(parseRecognition);
        const keptPhrases = phrases.filter(ph => gateTranscript(ph.text, ph.confidence, floor));
        const heard = { text: phrases.map(ph => ph.text).join(' ').trim(),
          confidence: phrases.reduce((low, ph) => ph.confidence == null ? low : (low == null ? ph.confidence : Math.min(low, ph.confidence)), null) };
        const kept = keptPhrases.map(ph => gateTranscript(ph.text, ph.confidence, floor)).join(' ').trim();
        const keptConfidence = keptPhrases.reduce((low, ph) => ph.confidence == null ? low : (low == null ? ph.confidence : Math.min(low, ph.confidence)), null);
        if (kept) return resolve({ ok: true, text: kept.slice(0, 4000), confidence: keptConfidence });
        // Heard SOMETHING, but not enough to act on. `ok:true` with an empty text and NO `error` field is the
        // contract the caller reads as "silence — listen again": setting `error` here would surface a red
        // failure in the panel for what is really just a quiet room.
        if (heard.text) return resolve({ ok: true, text: '', confidence: heard.confidence, dropped: 'below-threshold' });
        if (!error) return resolve({ ok: true, text: '' });
        if (error && error.name === 'AbortError') return resolve({ ok: false, text: '', error: 'aborted' });
        const timedOut = !!(error && (error.killed || error.code === 'ETIMEDOUT'));
        resolve({ ok: timedOut, text: '', error: timedOut ? 'no-speech' : 'native speech failed' });
      });
    });
  }

  async function recognize(params) {
    params = params || {};
    if (!status().available) return { ok: false, text: '', error: 'native speech is unavailable on this platform' };
    const wav = params.audioWav;
    if (!wav || !wav.length) return runRecognition(WINDOWS_SCRIPT, params.signal);
    const tempPath = path.join(tempDir, 'starnet-stt-' + randomUUID() + '.wav');
    try {
      await fsp.writeFile(tempPath, wav);
      // 16 kHz mono PCM16 (float32PcmToWav) → 32 bytes per millisecond after the 44-byte header.
      return await runRecognition(WINDOWS_WAV_SCRIPT, params.signal, tempPath, Math.max(0, wav.length - 44) / 32);
    } catch (_) {
      return { ok: false, text: '', error: 'native speech failed' };
    } finally {
      try { await fsp.unlink(tempPath); } catch (_) {}
    }
  }

  return { status, recognize };
}

module.exports = { WINDOWS_SCRIPT, WINDOWS_WAV_SCRIPT, NOISE_TOKENS, DEFAULT_MIN_CONFIDENCE, parseRecognition, gateTranscript, makeNativeStt };
